[package]
name = "gallsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.6.6"
gtk = "0.17.1"
glib = "0.17.10"
