[package]
name = "gallsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.16.2"
gtk4 = "0.5.4"
rename = "0.1.1"
